DECLARE @SQL NVARCHAR(MAX) = '';

SELECT @SQL = @SQL + 'ALTER TABLE ' + QUOTENAME(FK.TABLE_SCHEMA) + '.' + QUOTENAME(FK.TABLE_NAME) + 
    ' DROP CONSTRAINT ' + QUOTENAME(FK.CONSTRAINT_NAME) + ';' + CHAR(13)
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS FK
WHERE FK.CONSTRAINT_SCHEMA = 'dbo';

EXEC sp_executesql @SQL;

DECLARE @dropTables NVARCHAR(MAX) = '';

SELECT @dropTables = @dropTables + 'DROP TABLE ' + QUOTENAME(TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME) + ';' + CHAR(13)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'dbo';

EXEC sp_executesql @dropTables; 